name: Autograding Tests
on:
  push:
    branches:
      - main
    # paths-ignore:
    #   - '.github/**'
env:
  IMG_URL_riscv64: https://github.com/Azure-stars/testsuits-for-oskernel/releases/download/v0.2/sdcard-riscv64.img.gz # 镜像url
  IMG_URL_loongarch64: https://github.com/Azure-stars/testsuits-for-oskernel/releases/download/v0.2/sdcard-loongarch64.img.gz # 镜像url
  IMG_URL_aarch64: https://github.com/Azure-stars/testsuits-for-oskernel/releases/download/v0.2/sdcard-aarch64.img.gz # 镜像url
  IMG_URL_x86_64: https://github.com/Azure-stars/testsuits-for-oskernel/releases/download/v0.2/sdcard-x86_64.img.gz # 镜像url
  TIMEOUT: 1000 # 超时时间
  SCRIPT_REPO: https://github.com/oscontent25/EvaluationScript # 脚本仓库

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    env:
      qemu-version: 9.2.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly-2025-01-18
          components: rust-src, llvm-tools
          targets: x86_64-unknown-none, riscv64gc-unknown-none-elf, aarch64-unknown-none, aarch64-unknown-none-softfloat, loongarch64-unknown-none
      - uses: Swatinem/rust-cache@v2
      - run: cargo install cargo-binutils
      - uses: ./.github/workflows/setup-musl
        with:
          arch: riscv64
      - uses: ./.github/workflows/setup-musl
        with:
          arch: loongarch64
      - uses: ./.github/workflows/setup-musl
        with:
          arch: aarch64
      - uses: ./.github/workflows/setup-musl
        with:
          arch: x86_64
      - uses: ./.github/workflows/setup-qemu
        with:
          qemu-version: ${{ env.qemu-version }}
      - name: Build python environment
        run: sudo apt-get install -y python3 python3-pip

      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          repository: Mivik/starry-next
          ref: c4552466a5c57d1e0f8fcc10135e6f61e3fa79ab
          path: starry-next
      - name: Run testcases
        run: |
          cp testcase_list starry-next/apps/oscomp

          cd starry-next

          echo "Cloning repositories ..." || true
          git clone https://github.com/Mivik/arceos -b fs2-test .arceos --depth=1 || true

          ./scripts/set_ax_root.sh .arceos

          echo 'start---riscv64' >> output.txt
          make ARCH=riscv64 oscomp_run >> output.txt || true
          echo 'end---riscv64' >> output.txt

          echo 'start---aarch64' >> output.txt
          make ARCH=aarch64 oscomp_run >> output.txt || true
          echo 'end---aarch64' >> output.txt

          echo 'start---loongarch64' >> output.txt
          make ARCH=loongarch64 oscomp_run LOG=error >> output.txt || true
          echo 'end---loongarch64' >> output.txt

          echo 'start---x86_64' >> output.txt
          make ARCH=x86_64 ACCEL=n oscomp_run >> output.txt || true
          echo 'end---x86_64' >> output.txt

          cat output.txt
          mv output.txt ../output.txt

      - name: Download EvaluationScript
        run: |
          git clone ${{ env.SCRIPT_REPO }} .github/classroom

      - name: glibcbasic-test
        uses: oscontent25/os-autograding@master
        id: glibcbasic-test
        with:
          outputFile: output.txt
          scriptPath: .github/classroom/glibc-basic
      - name: glibclibctest-test
        uses: oscontent25/os-autograding@master
        id: glibclibctest-test
        with:
          outputFile: output.txt
          scriptPath: .github/classroom/glibc-libctest
      - name: glibclua-test
        uses: oscontent25/os-autograding@master
        id: glibclua-test
        with:
          outputFile: output.txt
          scriptPath: .github/classroom/glibc-lua
      - name: glibcbusybox-test
        uses: oscontent25/os-autograding@master
        id: glibcbusybox-test
        with:
          outputFile: output.txt
          scriptPath: .github/classroom/glibc-busybox
      - name: glibciozone-test
        uses: oscontent25/os-autograding@master
        id: glibciozone-test
        with:
          outputFile: output.txt
          scriptPath: .github/classroom/glibc-iozone
      - name: muslbasic-test
        uses: oscontent25/os-autograding@master
        id: muslbasic-test
        with:
          outputFile: output.txt
          scriptPath: .github/classroom/musl-basic
      - name: musllibctest-test
        uses: oscontent25/os-autograding@master
        id: musllibctest-test
        with:
          outputFile: output.txt
          scriptPath: .github/classroom/musl-libctest
      - name: musllua-test
        uses: oscontent25/os-autograding@master
        id: musllua-test
        with:
          outputFile: output.txt
          scriptPath: .github/classroom/musl-lua
      - name: muslbusybox-test
        uses: oscontent25/os-autograding@master
        id: muslbusybox-test
        with:
          outputFile: output.txt
          scriptPath: .github/classroom/musl-busybox
      - name: musliozone-test
        uses: oscontent25/os-autograding@master
        id: musliozone-test
        with:
          outputFile: output.txt
          scriptPath: .github/classroom/musl-iozone

      - name: Autograding Reporter
        uses: oscontent25/autograding-grading-reporter@v1
        env:
          GLIBCBASIC-TEST_RESULTS: "${{steps.glibcbasic-test.outputs.result}}"
          GLIBCLIBCTEST-TEST_RESULTS: "${{steps.glibclibctest-test.outputs.result}}"
          GLIBCLUA-TEST_RESULTS: "${{steps.glibclua-test.outputs.result}}"
          GLIBCBUSYBOX-TEST_RESULTS: "${{steps.glibcbusybox-test.outputs.result}}"
          GLIBCIOZONE-TEST_RESULTS: "${{steps.glibciozone-test.outputs.result}}"
          MUSLBASIC-TEST_RESULTS: "${{steps.muslbasic-test.outputs.result}}"
          MUSLLIBCTEST-TEST_RESULTS: "${{steps.musllibctest-test.outputs.result}}"
          MUSLLUA-TEST_RESULTS: "${{steps.musllua-test.outputs.result}}"
          MUSLBUSYBOX-TEST_RESULTS: "${{steps.muslbusybox-test.outputs.result}}"
          MUSLIOZONE-TEST_RESULTS: "${{steps.musliozone-test.outputs.result}}"
        with:
          runners: glibcbasic-test,glibclibctest-test,glibclua-test,glibcbusybox-test,glibciozone-test,muslbasic-test,musllibctest-test,musllua-test,muslbusybox-test,musliozone-test
          token: ${{ secrets.GITHUB_TOKEN }}
